uploads = []

[[generated]]
id = "Ogj-TRD6WNu9vdghQ1l7u"
uri = "file://artifacts/mockup-sandbox/public/images/bugatti.png"
type = "image"
title = "Bugatti Chiron parked outdoors"

[[generated]]
id = "tTYaUK0OB3e7tsfEtWJen"
uri = "file://artifacts/mockup-sandbox/public/images/iphone.png"
type = "image"
title = "iPhone 14 Pro lying flat"

[[generated]]
id = "-yQzUirabU5FIU4U4jphV"
uri = "file://artifacts/mockup-sandbox/public/images/textbook.png"
type = "image"
title = "Calculus university textbook"

[[generated]]
id = "9QUCgHibhVRgWuS_hmaIy"
uri = "file://artifacts/mockup-sandbox/public/images/guitar.png"
type = "image"
title = "Acoustic guitar"

[[generated]]
id = "N53xSTx7zJdkOX2b05U6t"
uri = "file://artifacts/mockup-sandbox/public/images/airpods.png"
type = "image"
title = "Apple AirPods in case"

[[outputs]]
id = "pSQM8naRgPxg8AFURXu3I"
uri = "file://artifacts/mockup-sandbox/public/images/macbook.jpg"
type = "image"
title = "A Macbook laptop on a desk"

[[outputs]]
id = "inAwphjU5aBBxbatYQZhW"
uri = "file://artifacts/mockup-sandbox/public/images/calculus-textbook.jpg"
type = "image"
title = "A thick math or calculus textbook"

[[outputs]]
id = "8Z5KL86DRhExdfIohhfAi"
uri = "file://artifacts/mockup-sandbox/public/images/guitar.jpg"
type = "image"
title = "An acoustic guitar"

[[outputs]]
id = "nXZFlcBKnlhUh5DYF8Vh8"
uri = "file://artifacts/mockup-sandbox/public/images/airpods-case.jpg"
type = "image"
title = "Apple AirPods charging case on a table"

[[outputs]]
id = "pYx-pRBKRgqqL48YfhGJX"
uri = "file://artifacts/xmum-market/public/apple-touch-icon.png"
type = "image"
title = "apple-touch-icon.png — 180×180"

[[outputs]]
id = "MW6R197sca49mDUi7obDH"
uri = "file://artifacts/xmum-market/public/favicon-96x96.png"
type = "image"
title = "favicon-96x96.png — 96×96"

[[outputs]]
id = "D1INP29mjJMgR2yDRpqkc"
uri = "file://artifacts/xmum-market/public/web-app-manifest-192x192.png"
type = "image"
title = "web-app-manifest-192x192.png — 192×192"

[[outputs]]
id = "bejcRByA1akP1uyPOiM21"
uri = "file://artifacts/xmum-market/public/web-app-manifest-512x512.png"
type = "image"
title = "web-app-manifest-512x512.png — 512×512"
