// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-layouts/BentoLayout.tsx": () => import("../components/mockups/homepage-layouts/BentoLayout.tsx"),
  "./components/mockups/homepage-layouts/FeedLayout.tsx": () => import("../components/mockups/homepage-layouts/FeedLayout.tsx"),
  "./components/mockups/homepage-layouts/MudahInspired.tsx": () => import("../components/mockups/homepage-layouts/MudahInspired.tsx"),
  "./components/mockups/homepage-layouts/SidebarLayout.tsx": () => import("../components/mockups/homepage-layouts/SidebarLayout.tsx")
};
